### PR TITLE
Dockerfile: containerize digsigserver

### PR DESCRIPTION
**Pull request by Lexmark-chad**
@madisongh , submitting a PR for your review.  It could use some updates to the documentation still for how to build & run the container.  If you think it's worthwhile to merge I can finish out the documentation and update the PR.  Right now it only supports L4T versions 32.5.2 and 32.7.2 because that is what I can easily test.

### CODE REVIEW

**Comment by madisongh** [comment]
@Lexmark-chad  I'm fine with pulling this in - maybe move it to a subdirectory and put a README.md there with whatever additional info you think is appropriate.  I'm not really a Docker user, but I think others would find this useful.

Thanks!

**Comment by Lexmark-chad** [comment]
Thanks for the feedback.  I like your suggestion and will start working on the changes.

**Comment by Lexmark-chad** [comment]
@madisongh , I think this is ready to go.  Sorry if you got spam'd with a bunch of email notifications as I updated the markdown!

**Comment by madisongh** [comment]
Thanks!

**Pull request merged**
